version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    env_file:
      - src/main/.env
    networks:
      - datingapp-network
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]

networks:
  datingapp-network:
    driver: bridge

volumes:
  db-data: